config/routes.rb
SampleApp::Application.routes.draw do
  resources :userts
  resources :sessions, only: [:new, :create, :destroy]

  root              to: 'static_pages#home'

  match '/signup',  to: 'userts#new',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/usert.rb
# == Schema Information
#
# Table name: userts
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Usert < ActiveRecord::Base
  # ===== Modifiers =====

  attr_accessible :email, :name, :password, :password_confirmation

  # ===== Validations =====

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  # ===== Secure password =====

  has_secure_password

  # ===== Normalize email =====

  before_save { |usert| usert.email = email.downcase }

  # ===== Remember Token =====

  before_save :create_remember_token

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    usert = Usert.find_by_email(params[:session][:email].downcase)
    if usert && usert.authenticate(params[:session][:password])
      sign_in usert
      redirect_to usert
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/userts_controller.rb
class UsertsController < ApplicationController
  def index

  end

  def show
    @usert = Usert.find(params[:id])
  end

  def new
    @usert = Usert.new
  end

  def create
    @usert = Usert.new(params[:usert])
    if @usert.save
      sign_in @usert
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @usert
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(usert)
    cookies.permanent[:remember_token] = usert.remember_token
    self.current_user = usert
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(usert)
    @current_user = usert
  end

  def current_user
    @current_user ||= Usert.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/userts_helper.rb
module UsertsHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "http://railstutorial.org/"} Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li= link_to "About",   '#'
      %li= link_to "Contact", '#'
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
.site-header
  %header
    .logo
      = link_to 'Spielerei', root_path, id: "logo"
    %nav.header-nav
      %ul
        %li= link_to 'Home',    root_path
        %li= link_to 'About',   about_path
        %li= link_to 'Help',    help_path
        %li= link_to 'Contact', contact_path
        - if signed_in?
          %li= link_to 'Users',   '#'
          %li#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              Account
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'Profile',  current_user
              %li= link_to 'Settings', '#'
              %li.divider
              %li= link_to 'Sign out', signout_path, method: 'delete'
        - else
          %li= link_to 'Sign in',  signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title yield(:title)
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container.site-content
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      = render 'layouts/footer'

      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if @usert.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(@usert.errors.count, "error")}.
    %ul
      - @usert.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<blockquote>
  <p>Titel</p>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</blockquote>

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%h1 About Us
%blockquote
  %p Titel
  %p
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')
%h1 Contact
%p
  Contact Ruby on Rails Tutorial about the sample app at the
  = succeed "." do
    %a{:href => "http://railstutorial.org/contact"} contact page

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 Help
%p
  Get help on the Ruby on Rails Tutorial at the
  = succeed "." do
    %a{:href => "http://railstutorial.org/help"} Rails Tutorial help page
  To get help on this sample app, see the
  = succeed "." do
    %a{:href => "http://railstutorial.org/book"} Rails Tutorial book

app/views/static_pages/home.html.haml
.center.hero-unit
  %h1 Welcome to the Sample App
  %h2
    This is the home page for the
    %a{href: "http://railstutorial.org/"} Ruby on Rails Tutorial sample application.

  = link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"

= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/userts/new.html.haml
- provide(:title, 'Sign Up')
%h1.center Sign Up

.row
  .span6.offset3
    = render 'shared/error_messages'
    = form_for(@usert) do |f|
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation
      %p
        = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/userts/show.html.haml
- provide(:title, @usert.name)
.row
  %aside.span4
    %section
      %h1
        = gravatar_for @usert
        = @usert.name